### ISSUE TITLE
R2L: time rules breaking

### ISSUE THREAD

**Issue by williampma** [opencog/relex#213]
The rules for time does not account for the new way preposition are handled by RelEx, and is not executing.

**Comment by linas** [comment]
So, we are not using relex R2L any more, and this can be closed, right?

**Comment by anitzkin** [comment]
Sorry, I didn't get to reply to this earlier.  Yeah, the time rules never
would have worked, because the way they were written only accounted for 2-3
cherry picked time expressions out of of the 1000's of time expressions in
English, so I made them all into "adverbial" prepositional phrases as
that's what they are.  That way any answer to the questions when, why, how,
or where gets the correct logical form, not just a few expressions that
happned to be remembered by whoever coded it before.
