### ISSUE TITLE
WordSequenceLink Numbering not reset

### ISSUE THREAD

**Issue by AmeBel** [opencog/relex#222]
The NumberNode associated with each word in a sentence through a WordSequenceLink are getting incremented across sequential parses, when using relex in server mode.

**Comment by williampma** [comment]
I think I see it.  OpenCogScheme object is created once per start and it is reused for all sentences, so `seqno` never get set back to 1.

Maybe the solution is to set it to 1 inside OpenCogScheme::setParse(..) method.

**Comment by williampma** [comment]
I wonder if that is done on purpose though.  Maybe there's some usage for the NumberNode keep incrementing.

**Comment by linas** [comment]
It was not reset to 1 on purpose, so that you can easily find all later words. Otherwise, you would have to ask  "give me a word with a higher number, or a word in a sentence with a higher sentence number, or a word in a paragraph with a higher paragraph number".  which is much more complicated to query.   This matters for anaphora, where you need to know word-order numbering between sentences, not just in one sentence.

It is important to know the order of the words in a sentence, but I've always found the WordSequenceLink  hard to use, mostly because it does not play nice with the pattern matcher.    There is no easy way to create a query that says "give me all words after this word".   You might hope that GreaterThanLink could do this, and I guess it can, but its kind-of bulky.

**Comment by AmeBel** [comment]
Good to know, thanks
