### ISSUE TITLE
scripts missing newer versions of openNLP and maxent in classpaths

### ISSUE THREAD

**Issue by mjsduncan** [opencog/relex#240]
i added these  .jar paths to match `build.xml` to all the .sh shell scripts that needed them so openNLP would work.  openNLP 1.6.0 also works.
````
/usr/local/share/java/opennlp-tools-1.5.3.jar:\
/usr/local/share/java/maxent-3.0.3.jar:\
````
i don't know enough java to figure out if openNLP is getting used in `ant test`, the number of correct parses doesn't increase.  it would be helpful to print out the openNLP version when it gets used along with the link-grammar and relex versions.

**Comment by linas** [comment]
You should have opened a pull request so that your changes could be merged. I just merged them now, by hand.

The *only* place where openNLP gets used is for sentence splitting -- determining where the ends of sentences are. Periods are not enough:  "Dr. Smith is late." the first period is not a sentence-ender.  

The default sentence splitter is already pretty good, and its mostly unlikely that OpenNLP improves on it, if at all. Thus, newer versions of OpenNLP will make NO DIFFERENCE AT ALL for the unit tests, and will make an almost indiscernable difference for "normal use".   Basically, we could (and maybe should??) rip out OpenNLP entirely.
