### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by mindpixel20** [opencog/relex#289]
Running into the same issue of 

`java.lang.UnsatisfiedLinkError: no link-grammar-java in java.library.path: [/usr/lib, /usr/lib/jni, /usr/local/lib, /usr/local/lib/jni]`

despite following current directions and relex alt directions and symlinking the libraries.

**Comment by linas** [comment]
Did you build and install link-grammar?  I guess you must have, ut I am guessing that the link-grammar java bindings failed to build.  This might be because the `jni.h` file was not found.  Pay close attention to what `configure` prints, when building link-grammar: it will inform you of any problems with building java.

**Comment by linas** [comment]
Closing, no response to debugging suggestion.
